### ISSUE TITLE
Regarding The Pip Install Gilda Library Installation 

### ISSUE THREAD

**Issue by bohrahusky** [indralab/gilda#47]
I am a post masters research associate at Pacific Northwest National Laboratory. 
We are working on covid knowledge graph generation project. 
We are using datasets from Indra and blender.

What we are doing in the code :
We do a ground id hunting procedure in those projects, where we look if an entry has a MESH:ID if not we look for CHEBI:ID else we go for the id. (with INDRA and BLENDER datasets)
We wanted to modularize the code more with Gilda API. 

A problem which I encountered while dealing with gilda library is I am not able to use the ground function in the Grounder class, because of the load_terms_file() function  
As it gives me a utf-8 encoding error. While loading the TSV file in the grounder class.

Solution done by me 
While if I create my own classes locally and then instantiate the grounder class with the changes of encoding it gives me no error and we are easily able to ground the database. 

Is there any help possible in the API or something??
Kindly Help

Thanking You 

Problem Encountered 

load_terms_file(terms_file):
    """Load a TSV file containing terms into a lookup dictionary.
    Parameters
    ----------
    terms_file : str
        Path to a TSV terms file with columns corresponding to the serialized
        elements of a Term.
    Returns
    -------
    dict
        A lookup dictionary whose keys are normalized entity texts, and values
        are lists of Terms with that normalized entity text.
    """
    with open(terms_file, 'r') as fh:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5728: character maps to <undefined>

Changes I made on local classes

load_terms_file(terms_file):
    """Load a TSV file containing terms into a lookup dictionary.
    Parameters
    ----------
    terms_file : str
        Path to a TSV terms file with columns corresponding to the serialized
        elements of a Term.
    Returns
    -------
    dict
        A lookup dictionary whose keys are normalized entity texts, and values
        are lists of Terms with that normalized entity text.
    """
    with open(terms_file, 'r' , encoding = “utf-8”) as fh:<--------------------------------------

Then it loads properly!.

Kind Regards 
Ankur Bohra 
Post Masters Research Associate 
PNNL

**Comment by bgyori** [comment]
Thanks @bohrahusky, I added the explicit encoding argument and released Gilda v0.5.3.

**Comment by bohrahusky** [comment]
$ pip install gilda==0.5.3
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
Could not fetch URL https://pypi.org/simple/gilda/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/gilda/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))) - skipping
ERROR: Could not find a version that satisfies the requirement gilda==0.5.3
ERROR: No matching distribution found for gilda==0.5.3

**Comment by bohrahusky** [comment]
> Thanks @bohrahusky, I added the explicit encoding argument and released Gilda v0.5.3.

$ pip install gilda==0.5.3
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /simple/gilda/
Could not fetch URL https://pypi.org/simple/gilda/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/gilda/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))) - skipping
ERROR: Could not find a version that satisfies the requirement gilda==0.5.3
ERROR: No matching distribution found for gilda==0.5.3

**Comment by bgyori** [comment]
I'm not sure what to make of that, 0.5.3 is definitely released on PyPI (https://pypi.org/project/gilda/0.5.3/). It looks like you might have an issue with the connection to PyPI itself.
