### ISSUE TITLE
Add minimum python version to setup.py

### ISSUE THREAD

**Issue by cthoyt** [indralab/gilda#5]
Is this project Python3.5+ or can we use f-strings?

I would love to replace the Term class with a dataclass, too!

**Comment by bgyori** [comment]
I kept it 3.5 in case we want to integrate it with INDRA directly and would like to keep it that way for the time being. I understand the urge to use new stuff but the first priority is broad compatibility.

**Comment by bgyori** [comment]
I'll close this for now, setup.py contains a list of classifiers indicating Python versions.
