### ISSUE TITLE
Compress gilda.resources data files (gilda_models.pkl and grounding_terms.tsv)

### ISSUE THREAD

**Issue by dhimmel** [indralab/gilda#59]
The data files for gilda in `.data/gilda/0.6.1` are on the larger size and have high compression ratios (via `gzip --keep --no-name`):

```
-rw-rw-r-- 1 dhimmel-rs dhimmel-rs  39M Sep 27 13:44 gilda_models.pkl
-rw-rw-r-- 1 dhimmel-rs dhimmel-rs  13M Sep 27 13:44 gilda_models.pkl.gz
-rw-rw-r-- 1 dhimmel-rs dhimmel-rs 201M Sep 27 13:44 grounding_terms.tsv
-rw-rw-r-- 1 dhimmel-rs dhimmel-rs  34M Sep 27 13:44 grounding_terms.tsv.gz
```

Might make sense to store these files in a compressed format? If using multiple versions of gilda, these file sizes can begin to add up. Also initial download would be faster.

**Comment by bgyori** [comment]
Thanks @dhimmel, that's a good idea, we can implement it for the next release!

**Comment by dhimmel** [comment]
Thanks for the reply. `xz` will give you the best compression ratios with decent decompression time. Some users are unfamiliar with `xz`, but not sure if that matters here.

If using gzip and reproducible checksums matter, you have to take the extra step of `--no-name` via the command line or `mtime=0` in Python or `compression={"method": 'gzip', "mtime": 0}` with `pandas.DataFrame.to_csv`.
