### ISSUE TITLE
Handle accented characters

### ISSUE THREAD

**Issue by dhimmel** [indralab/gilda#62]
From reading the preprint, Gilda is quite capable at dealing with variations in how greek and latin characters are written. I noticed however that it doesn't connect characters with their accented versions. Here's an example:

`gilda.ground("Aymé-Gripp syndrome")` (with accent) returns only `EFO:0009020`

```
ScoredMatch(Term(aymégripp syndrome,Aymé-Gripp syndrome,EFO,0009020,Aymé-Gripp syndrome,name,efo,None),0.7777777777777778,Match(query=Aymé-Gripp syndrome,ref=Aymé-Gripp syndrome,exact=True,space_mismatch=False,dash_mismatches={},cap_combos=[]))
```

`gilda.ground("Ayme-Gripp syndrome")` (no accent) returns only `DOID:0111688`

```
ScoredMatch(Term(aymegripp syndrome,Ayme-Gripp syndrome,DOID,DOID:0111688,Ayme-Gripp syndrome,name,doid,None),0.7777777777777778,Match(query=Ayme-Gripp syndrome,ref=Ayme-Gripp syndrome,exact=True,space_mismatch=False,dash_mismatches={},cap_combos=[]))
```

Expected behavior would be to return both `EFO:0009020` and `DOID:0111688` for either query (with or without the `é`), because search terms could normalize away the accent. Not saying the score should be the same, but that accents don't by themselves prevent a match.

**Comment by dhimmel** [comment]
> it's relatively rare statistically to encounter this case

Yeah, a few rare diseases come to mind where the accents will cause problems. Also mentioning a couple other types of problems:

Here's one with an accent as well as punctuation variants in the apostrophe `Löfgren’s syndrome` (`EFO:0009466`). Changing the apostrophe to `'` leads to no results:

```
term_df.query('''entry_name=="Löfgren's syndrome"''')
```

Another pathological case is unicode subscripts/superscripts like `Bi₇O₉I₃`... should they match non-subscripted versions like `Bi7O9I3`?

Also variations in hyphen/dash type in `G(8–O–4)S(8–5)G`.

**Comment by bgyori** [comment]
Okay, these are good. All of the cases in this thread so far can be canonicalized to ASCII using unidecode with the expected results, so I think that will be the most practical solution.
