### ISSUE TITLE
How to subset matches to specific entity types?

### ISSUE THREAD

**Issue by dhimmel** [indralab/gilda#63]
A common use case is using Gilda to normalize text strings that were detected by NER (named entity recognition) where there NERs are of a single entity type. The entity type might be diseases, genes, pathways, or genes + proteins + families. Currently, it doesn't appear possible to specify an entity type for which Gilda will restrict matches to.

To complicate matters, some ontologies contain multiple entity types and some entity types are covered by multiple ontologies.

For example, to filter for MeSH diseases, one must look at the tree numbers to detect top level categories and do something like:

```py
# regex patterns to include
include = [
    # Category C is for diseases
    # https://www.nlm.nih.gov/bsd/indexing/training/CATC_010.html
    r"C[0-9]{2}",
    # F03 mental disorders
    # https://www.nlm.nih.gov/bsd/indexing/training/CATF_010.html
    "F03",
]
# regex patterns to exclude
# exclude takes precedent over include
exclude = [
    "C26",  # Wounds and Injuries
]
```

Accordingly, identifying the set of terms that correspond to a specific entity type is not trivial, although it would provide great user convenience.

Prior to Gilda adopting any conception of entity types, users are still able to compute relevant term subsets for their grounding queries. What is the recommended way for applying a term set filter:

1. creating a custom terms table or filtering the terms table in memory prior to `gilda.ground`?
2. running matches on the full term set and then filtering results / scored_matches for the desired term set?

Any recommendations on the easiest way to do this?

**Comment by cthoyt** [comment]
Really interesting question, @dhimmel. We've actually been considering in the last few weeks how to type entities in Gilda as well as in a few of our other related projects. I'll leave it to @bgyori to comment on how it might or might not end up inside Gilda at some point.

As a side note, the fact that Gilda doesn't currently implement a type system gives it a disadvantage for each individual task in the BioCreative benchmarking evaluation, where the other models were specifically trained only for a single entity (or namespace). There are several tricky (but perhaps less practical) ways we could have got around this, but in the end, a lot of the choices were to support the inclusion of Gilda in places like the [INDRA database search](https://db.indra.bio/search) where users also won't input type information.

**Comment by bgyori** [comment]
Interesting question! Inferring types for each entry is a very tricky task and I think there are good reasons for why Gilda shouldn't necessarily attempt solving this. First, it requires stronger integration with external resources, and more sophisticated ontology structures to assign appropriate entity types to entries (working with MeSH tree numbers, GO hierarchy, resolving multiple inheritance, etc.). Second, I believe the definition of entity types is often use-case specific - it is unlikely that any specific choice made in Gilda would be a perfect fit for someone else's concept of the appropriate entity type classes.

So even in my own usage of Gilda, I used either your suggested strategies (1) or (2) when this issue needed to be addressed. For (1), creating a custom Gilda instance with specific resources loaded is a great idea if you want a custom grounder for a restricted set of entities e.g., anatomical regions and tissues (this is just one example I've actually done). It has the advantage that disambiguation will not be an issue, you will never accidentally ground something you know is a tissue to a gene. You can also instantiate Gilda with other resources that aren't by default in Gilda from OBO files, for instance, I've done this with the Taxonomy before.

As for (2), that is also often a useful thing to do. For instance, if you want to come up with some custom post-processing logic for scored matches where you prioritize one match over another if it's from a preferred namespace and its score is not too low. This can also be useful if you want to implement your own downstream re-mapping logic. For example, you might have mappings from UniProt, HGNC and MeSH to genes in Entrez, and you want to collect all the Gilda matches to the former namespaces and map them your preferred namespace.

**Comment by dhimmel** [comment]
The `namespaces` option of `gilda.ground` introduced in https://github.com/indralab/gilda/pull/89 seems highly relevant and helpful here!

**Comment by cthoyt** [comment]
It's definitely a good solution for many common cases where there's a nomenclature that covers a single entity type. FYI we have some ideas on how to address this for other nomenclatures with a small number of different entity types (e.g., GO has 3 entity types) or potentially very many entity types (e.g., MeSH, NCIT) that we might also work on in the future.

Another place to look in this realm is [COB](https://obofoundry.org/ontology/cob), which is trying to provide a more standardized type system across the OBO universe
