### ISSUE TITLE
HGNC gene name alias "FP prostanoid receptor" is not matched

### ISSUE THREAD

**Issue by dhimmel** [indralab/gilda#78]
The following currently returns zero matches:

```py
gilda.ground("FP prostanoid receptor")
```

Even though HGNC [contains](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:9600) the following:

- Alias names: FP prostanoid receptor

Can also see this via `http://rest.genenames.org/fetch/hgnc_id/HGNC:9600`:

```xml
<arr name="alias_name">
<str>FP prostanoid receptor</str>
</arr>
```

Does gilda not use HGNC alias names when searching for matches?

**Comment by dhimmel** [comment]
Also noting that NCBI gene [has](https://www.ncbi.nlm.nih.gov/gene/?term=5737) a nice list of names for protein products of a gene:

> ![image](https://user-images.githubusercontent.com/1117703/151856752-98e56b5a-b412-4d37-8b22-f2feb260bfdb.png)

Not sure if Gilda intends to tag proteins as genes, but this often is helpful. Here are the [ncbi docs](https://www.ncbi.nlm.nih.gov/books/NBK3841/#EntrezGene.General_Protein_Information) for this section:

> This section applies only to genes that encode proteins. It reports the name or names that have been assigned to proteins encoded by the gene and provides other descriptive text. The names are as annotated on the RefSeq protein, when that protein is available. The sources of these names include model organism databases, annotation on public sequence databases, and curation by RefSeq staff.

**Comment by bgyori** [comment]
I've been working on this but ran into a few issues. First, HGNC has some quality issues when it comes to these alias names that I've reported e.g., 

![image](https://user-images.githubusercontent.com/5939016/156830196-bef77383-0549-4681-b48e-88e43abd3242.png)

and second, many of the alias gene names listed here are disease names (presumably the given gene is associated with the disease) that interfere with synonyms for actual diseases - I'm testing ways to automatically exclude these.

**Comment by dhimmel** [comment]
> HGNC has some quality issues when it comes to these alias names that I've reported

Thanks for reporting! Always fun to find errors like this in such foundational resources, which probably many others have seen but failed to report.

> many of the alias gene names listed here are disease names (presumably the given gene is associated with the disease) that interfere with synonyms for actual diseases - I'm testing ways to automatically exclude these

Do disease names that are also gene aliases need to be excluded? Or perhaps could they match but with a lower score? As noted in https://github.com/indralab/gilda/issues/63, for our use cases, we tend to know the entity type that we are trying to normalize, because we're mapping string entities of known types or because we've run named entity recognition to detect the type. Hence, I lean towards gilda being able to map both a gene and a disease if they share a term (assuming that I'll probably filter out one of those matches anyways just on entity type).

**Comment by dhimmel** [comment]
Noting the code for `generate_hgnc_terms`:

https://github.com/indralab/gilda/blob/716584a098fed1a7ab412426c22f36232a765208/gilda/generate_terms.py#L40-L94
